// src/features/lists/components/list-description.tsx
import type { List, ListItem } from '@/types/lists';

import { useEffect, useState } from 'react';

import { Link } from '@tanstack/react-router';
import { toast } from 'sonner';

import { formatElapsedTime } from '@/lib/time';
import { Route as CollectionPageRoute } from '@/routes/(user)/$username/collections/$slug.index';

type ListData = {
  list: List;
  isLiked: boolean;
  isSaved: boolean;
  listItems: ListItem[];
};

type ListDescriptionProps = {
  listData: ListData | undefined;
};

export default function ListDescription({ listData }: ListDescriptionProps) {
  const [displayData, setDisplayData] = useState<ListData>();

  const { username } = CollectionPageRoute.useParams();

  const [hovering, setHovering] = useState(false);

  // Keep UI in sync with server data after mutations
  useEffect(() => {
    if (listData) {
      setDisplayData(listData);
    }
  }, [listData]);

  return (
    displayData && (
      <div className="mb-8">
        <h2 className="mb-1 text-lg leading-snug font-bold break-words whitespace-normal md:text-xl">
          {displayData.list.name}
        </h2>
        <h3 className="text-gray mb-0.5 text-sm font-medium md:text-base">
          Collection by{' '}
          <Link
            to="/home"
            aria-disabled
            className="font-bold opacity-100 transition-colors duration-200"
            disabled
          >
            {username}
          </Link>
        </h3>

        <p
          onMouseEnter={() => setHovering(true)}
          onMouseLeave={() => setHovering(false)}
          className="text-medium text-gray relative h-5 w-fit cursor-default text-xs md:text-sm"
        >
          {getElapsedTimeText(hovering, displayData.list)}
        </p>
      </div>
    )
  );
}

function getElapsedTimeText(hovering: boolean, list: List) {
  let elapsedCreateTime = '';
  let elapsedUpdateTime = '';

  try {
    if (list.updatedAt && !elapsedUpdateTime) {
      const updatedAt = formatElapsedTime(list.updatedAt);
      elapsedUpdateTime = updatedAt;
    }

    if (list.createdAt && !elapsedCreateTime) {
      const createdAt = formatElapsedTime(list.createdAt);
      elapsedCreateTime = createdAt;
    }
  } catch (error) {
    if (error instanceof Error) {
      toast.error('Something went wrong while calculating elapsed time!');
    }
  }

  if (hovering && elapsedUpdateTime) {
    return `Published ${elapsedCreateTime} ago`;
  }

  if (elapsedUpdateTime) {
    return `Updated ${elapsedUpdateTime} ago`;
  }

  if (!elapsedUpdateTime) {
    return `Published ${elapsedCreateTime} ago`;
  }
}

// src/lib/components/lists/list-description.svelte
<script lang="ts">
	import type { ListData } from '$types/lists';
	import type { RouteParams } from '../../../routes/[username]/collections/[slug]/$types';

	import { getElapsedTimeText } from '$utils/time';

	import { resolve } from '$app/paths';
	import { page } from '$app/state';

	interface Props {
		listData: ListData;
	}

	let { listData }: Props = $props();

	const { username } = page.params as RouteParams;

	let displayData: ListData = $state();
	let isHovering = $state(false);

	// Keep UI in sync with server data after mutations
	$effect(() => {
		if (listData) {
			displayData = listData;
		}
	});
</script>

{#if displayData}
	<div class="mb-8">
		<h2 class="mb-1 text-lg leading-snug font-bold wrap-break-word whitespace-normal md:text-xl">
			{displayData.list.name}
		</h2>
		<h3 class="mb-0.5 text-sm font-medium text-gray md:text-base">
			Collection by
			<a
				href={resolve('/[username]', { username })}
				class="font-bold opacity-100 transition-colors duration-200"
			>
				{username}
			</a>
		</h3>

		<p
			onmouseenter={() => (isHovering = true)}
			onmouseleave={() => (isHovering = false)}
			class="text-medium relative h-5 w-fit cursor-default text-xs text-gray md:text-sm"
		>
			{getElapsedTimeText(isHovering, displayData.list)}
		</p>
	</div>
{/if}
