// src/features/lists/components/popular-list-card.tsx
import type { PopularList } from '@/types/lists';

import { Link } from '@tanstack/react-router';

import PopularListPreview from './popular-list-preview';

type PopularListProps = {
  item: PopularList;
};

export default function PopularListCard({ item }: PopularListProps) {
  return (
    <Link
      to="/$username/collections/$slug"
      params={{ username: item.username, slug: item.slug }}
      className="group hover:bg-background-light/40 bg-background relative flex flex-col overflow-hidden rounded-lg border border-white/10 transition-colors"
    >
      <div className="h-30 w-full md:h-36 lg:h-44">
        <PopularListPreview username={item.username} slug={item.slug} />
      </div>
      <div className="p-3">
        <div className="flex items-start justify-between gap-2">
          <h3 className="text-foreground line-clamp-2 text-sm font-semibold group-hover:text-white">
            {item.name}
          </h3>
          <span className="rounded-full bg-white/5 px-2 py-0.5 text-[11px] whitespace-nowrap text-white/80">
            {item.viewCount.toLocaleString()} views
          </span>
        </div>
        <p className="mt-2 text-xs text-white/60">@{item.username}</p>
      </div>
    </Link>
  );
}

// src/lib/components/lists/popular-list-card.svelte
<script lang="ts">
	import type { PopularList } from '$types/lists';

	import { resolve } from '$app/paths';

	import PopularListPreview from './popular-list-preview.svelte';

	interface Props {
		list: PopularList;
	}

	let { list }: Props = $props();

	let username = $derived(list.username);
	let slug = $derived(list.slug);
	let name = $derived(list.name);
</script>

<a
	href={resolve('/[username]/collections/[slug]', { username, slug })}
	class="group relative flex flex-col overflow-hidden rounded-lg border border-white/10 bg-background transition-colors hover:bg-background-light/40"
>
	<div class="h-30 w-full shrink-0 md:h-36 lg:h-44">
		<PopularListPreview {username} {slug} />
	</div>
	<div class="flex h-full flex-col items-start justify-between p-3">
		<h3 class="line-clamp-2 text-sm font-semibold text-foreground group-hover:text-white">
			{name}
		</h3>
		<p class="mt-2 text-sm text-white/60">@{username}</p>
	</div>
</a>
