// src/features/lists/components/popular-list-card-skeleton.tsx
export default function PopularListCardSkeleton() {
  return (
    <div className="relative flex flex-col overflow-hidden rounded-lg border border-white/10 bg-white/[0.02] animate-pulse">
      <div className="w-full h-36 sm:h-40 md:h-44 lg:h-48 xl:h-52 bg-white/[0.06]" />
      <div className="p-3 space-y-2">
        <div className="h-4 w-3/4 rounded bg-white/[0.06]" />
        <div className="h-3 w-1/3 rounded bg-white/[0.06]" />
      </div>
    </div>
  );
}

// src/lib/components/lists/popular-list-card-skeleton.svelte
<div
	class="relative flex animate-pulse flex-col overflow-hidden rounded-lg border border-white/10 bg-white/2"
>
	<div class="h-36 w-full bg-white/6 sm:h-40 md:h-44 lg:h-48 xl:h-52"></div>
	<div class="space-y-2 p-3">
		<div class="h-4 w-3/4 rounded bg-white/6"></div>
		<div class="h-3 w-1/3 rounded bg-white/6"></div>
	</div>
</div>
