// src/lib/components/lists/popular-lists-grid.svelte
<script lang="ts">
	import { createQuery } from '@tanstack/svelte-query';
	import { getUserLists } from '$services/lists';

	import PopularListCardSkeleton from '$components/lists/popular-list-card-skeleton.svelte';
	import PopularListCard from '$components/lists/popular-list-card.svelte';

	const listQuery = createQuery(() => ({
		queryKey: ['user-lists', 'framerate'],
		queryFn: () => getUserLists('framerate'),
		staleTime: 5 * 60 * 1000,
		gcTime: 10 * 60 * 1000
	}));

	let data = $derived(listQuery.data);
</script>

{#if listQuery.error}
	<div class="mx-auto py-10 text-center text-sm text-white/70">Failed to load collections.</div>
{/if}

<div class="animate-fade-in">
	<h2 class="mt-1 mb-4 text-lg font-medium md:text-xl">Popular Collections</h2>
	<div class="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4">
		{#if listQuery.isLoading && !data}
			{#each Array.from({ length: 10 }), index (index)}
				<PopularListCardSkeleton />
			{/each}
		{/if}

		{#if data}
			{#each data as list (list.id)}
				<PopularListCard {list} />
			{/each}
		{/if}
	</div>
</div>

// src/features/lists/components/popular-lists-grid.tsx
import { useQuery } from '@tanstack/react-query';

import PopularListCard from '@/features/lists/components/popular-list-card';
import PopularListCardSkeleton from '@/features/lists/components/popular-list-card-skeleton';
import { getPopularLists } from '@/server/lists';

export default function PopularListsGrid() {
  const { data, isFetching, error } = useQuery({
    queryKey: ['popular-lists'],
    queryFn: () => getPopularLists(24),
    staleTime: 5 * 60 * 1000,
    gcTime: 10 * 60 * 1000,
  });

  if (error) {
    return (
      <div className="mx-auto py-10 text-center text-sm text-white/70">
        Failed to load popular collections.
      </div>
    );
  }

  return (
    <div className="animate-fade-in">
      <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4">
        {isFetching &&
          (!data || data.length === 0) &&
          Array.from({ length: 10 }).map((_, i) => (
            <PopularListCardSkeleton key={i} />
          ))}

        {data?.map((item) => (
          <PopularListCard key={item.id} item={item} />
        ))}
      </div>
    </div>
  );
}
