// src/lib/components/lists/side-card.svelte
<script lang="ts">
	import type { ListData } from '$types/lists';
	import type { RouteParams } from '../../../routes/[username]/collections/[slug]/edit/$types';

	import { useQueryClient } from '@tanstack/svelte-query';
	import { addListAction, deleteListAction } from '$services/actions';
	import { deleteList } from '$services/lists';
	import { toast } from 'svelte-sonner';

	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { page } from '$app/state';

	import MediaActionIcon from '$components/icons/media-actions-icons.svelte';
	import * as Dialog from '$components/ui/dialog/index';
	import { authClient } from '$lib/auth-client';

	interface Props {
		listData: ListData;
	}

	let { listData }: Props = $props();
	let displayData: ListData = $state();
	let likeCount = $state(0);
	let saveCount = $state(0);
	let isLiked = $state(false);
	let isSaved = $state(false);

	const { username, slug } = page.params as RouteParams;

	const queryClient = useQueryClient();

	const activeUser = authClient.useSession();

	const formatter = Intl.NumberFormat('en', { notation: 'compact' });

	// Keep UI in sync with server after mutations and invalidations
	$effect(() => {
		if (listData) {
			displayData = listData;
			likeCount = listData.list.likeCount;
			saveCount = listData.list.saveCount;
			isLiked = listData.isLiked;
			isSaved = listData.isSaved;
		}
	});

	async function updateLike() {
		if (displayData) {
			const list = displayData.list;

			if (!isLiked) {
				likeCount++;
				isLiked = true;
				try {
					await addListAction(list.id, 'like');
				} catch {
					toast.error('Failed to like list! Please try again later');
					likeCount--;
					isLiked = false;
				}
			} else {
				likeCount--;
				isLiked = false;
				try {
					await deleteListAction(list.id, 'like');
				} catch {
					toast.error('Failed to unlike list! Please try again later');
					likeCount++;
					isLiked = true;
				}
			}

			queryClient.invalidateQueries({
				queryKey: ['list-items', username, slug]
			});
		}
	}

	async function updateSave() {
		if (displayData) {
			const list = displayData.list;

			if (!isSaved) {
				saveCount++;
				isSaved = true;
				try {
					await addListAction(list.id, 'save');
				} catch {
					toast.error('Failed to save list! Please try again later');
					saveCount--;
					isSaved = false;
				}
			} else {
				saveCount--;
				isSaved = false;
				try {
					await deleteListAction(list.id, 'save');
				} catch {
					toast.error('Failed to unsave list! Please try again later');
					saveCount++;
					isSaved = true;
				}
			}

			queryClient.invalidateQueries({
				queryKey: ['list-items', username, slug]
			});
		}
	}

	async function handleDelete() {
		if (displayData) {
			try {
				const deleted = await deleteList(displayData.list.id);
				if (deleted) toast.success('List deleted');
				queryClient.invalidateQueries({ queryKey: ['lists'] });
				goto(resolve('/collections'));
			} catch {
				toast.error('Failed to delete list! Please try again later');
			}
		}
	}

	let list = $derived(displayData?.list);
	let activeUserId = $derived($activeUser.data?.user.id);
	let isListOwner = $derived(list?.userId === activeUserId);
</script>

{#if displayData && displayData.listItems?.length > 0}
	<aside
		class="relative order-1 flex w-full flex-col items-center self-start rounded-md border border-white/5 bg-background p-3 shadow-md md:order-2 md:w-auto md:p-4 lg:p-6"
	>
		{#if isListOwner}
			<div class="mb-6 flex gap-3">
				<a
					href={resolve('/[username]/collections/[slug]/edit', { username, slug })}
					class="transiton-colors ease rounded-md border border-white/5 bg-[#28292d] px-4 py-2 font-medium duration-150 hover:border-white/10 hover:bg-transparent"
				>
					Edit
				</a>

				<Dialog.Root>
					<Dialog.Trigger>
						{#snippet child({ ...props })}
							<button
								class="ease cursor-pointer rounded-md border border-white/5 bg-[#28292d] px-4 py-2 font-medium transition-colors duration-150 hover:border-red-500 hover:bg-transparent"
							>
								Delete
							</button>
						{/snippet}
					</Dialog.Trigger>

					<Dialog.Content>
						<Dialog.Header>
							<Dialog.Title>Delete this list?</Dialog.Title>
							<Dialog.Description
								>This action cannot be undone. This will permanently delete your list and its
								content, including metadata such as likes, saves, and views.</Dialog.Description
							>
						</Dialog.Header>

						<Dialog.Footer>
							<Dialog.Close>
								<button
									class="inline-flex h-9 cursor-pointer items-center justify-center rounded-md border border-background-light bg-transparent px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-background-light hover:text-foreground"
								>
									Cancel
								</button>
							</Dialog.Close>
							<Dialog.Close>
								<button
									onclick={handleDelete}
									class="inline-flex h-9 cursor-pointer items-center justify-center rounded-md border-red-800 bg-red-700 px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-red-800"
								>
									Delete
								</button>
							</Dialog.Close>
						</Dialog.Footer>
					</Dialog.Content>
				</Dialog.Root>
			</div>
		{/if}

		<div class="flex w-full items-center justify-center gap-10 text-[#555] md:gap-6">
			<div class="flex items-center justify-center gap-2">
				<MediaActionIcon
					component="heart"
					fill="#333"
					onclick={() => updateLike()}
					classes={[
						isLiked ? 'fill-[#FF153A]' : '',
						'hover:fill-[#FF153A] cursor-pointer ease transition-all duration-150 active:scale-90 h-6'
					]}
				/>
				<p class="cursor-default">{formatter.format(likeCount)}</p>
			</div>

			<div class="flex items-center justify-center gap-2">
				<MediaActionIcon
					component="bookmark"
					fill="#333"
					onclick={() => updateSave()}
					classes={[
						isSaved ? 'fill-[#32EC44]' : '',
						'hover:fill-[#32EC44] cursor-pointer ease transition-all duration-150 active:scale-90 h-6'
					]}
				/>
				<p class="cursor-default">{formatter.format(saveCount)}</p>
			</div>
		</div>
	</aside>
{/if}

// src/features/lists/components/side-card.tsx
import type { List, ListItem } from '@/types/lists';

import { useEffect, useState } from 'react';

import { useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate } from '@tanstack/react-router';
import { toast } from 'sonner';

import Dialog from '@/components/dialog';
import {
  BookmarkIcon,
  HeartIcon,
} from '@/components/icons/media-actions-icons';
import { authClient } from '@/lib/auth-client';
import { Route as CollectionPageRoute } from '@/routes/(user)/$username/collections/$slug.index';
import { addListAction, deleteListAction } from '@/server/actions';
import { deleteList } from '@/server/lists';
import { useListStore } from '@/store/lists/list-store';

type ListData = {
  list: List;
  isLiked: boolean;
  isSaved: boolean;
  listItems: ListItem[];
};

type SideCardProps = {
  listData: ListData | undefined;
};

export default function SideCard({ listData }: SideCardProps) {
  const [displayData, setDisplayData] = useState<ListData>();
  const [likeCount, setLikeCount] = useState(0);
  const [saveCount, setSaveCount] = useState(0);
  const [isLiked, setIsLiked] = useState(false);
  const [isSaved, setIsSaved] = useState(false);

  const { username, slug } = CollectionPageRoute.useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const activeUser = authClient.useSession();

  const removeList = useListStore.use.removeList();

  const formatter = Intl.NumberFormat('en', { notation: 'compact' });

  // Keep UI in sync with server after mutations and invalidations
  useEffect(() => {
    if (listData) {
      setDisplayData(listData);
      setLikeCount(listData.list.likeCount);
      setSaveCount(listData.list.saveCount);
      setIsLiked(listData.isLiked);
      setIsSaved(listData.isSaved);
    }
  }, [listData, setIsLiked, setIsSaved]);

  async function updateLike() {
    if (displayData) {
      const list = displayData.list;

      if (!isLiked) {
        setLikeCount((v) => v + 1);
        setIsLiked(true);
        try {
          await addListAction(list.id, 'like');
        } catch {
          toast.error('Failed to like list! Please try again later');
          setLikeCount((v) => v - 1);
          setIsLiked(false);
        }
      } else {
        setLikeCount((v) => v - 1);
        setIsLiked(false);
        try {
          await deleteListAction(list.id, 'like');
        } catch {
          toast.error('Failed to unlike list! Please try again later');
          setLikeCount((v) => v + 1);
          setIsLiked(true);
        }
      }

      queryClient.invalidateQueries({
        queryKey: ['list-items', username, slug],
      });
    }
  }

  async function updateSave() {
    if (displayData) {
      const list = displayData.list;

      if (!isSaved) {
        setSaveCount((v) => v + 1);
        setIsSaved(true);
        try {
          await addListAction(list.id, 'save');
        } catch {
          toast.error('Failed to save list! Please try again later');
          setSaveCount((v) => v - 1);
          setIsSaved(false);
        }
      } else {
        setSaveCount((v) => v - 1);
        setIsSaved(false);
        try {
          await deleteListAction(list.id, 'save');
        } catch {
          toast.error('Failed to unsave list! Please try again later');
          setSaveCount((v) => v + 1);
          setIsSaved(true);
        }
      }

      queryClient.invalidateQueries({
        queryKey: ['list-items', username, slug],
      });
    }
  }

  async function handleDelete() {
    if (displayData) {
      try {
        const deleted = await deleteList(displayData.list.id);
        removeList(deleted.id);
        toast.success('List deleted');
        queryClient.invalidateQueries({ queryKey: ['lists'] });
        navigate({ to: '/collections' });
      } catch {
        toast.error('Failed to delete list! Please try again later');
      }
    }
  }

  return (
    displayData && (
      <aside className="bg-background relative order-1 flex w-full flex-col items-center self-start rounded-md border border-white/5 p-3 shadow-md md:order-2 md:w-auto md:p-4 lg:p-6">
        {activeUser.data &&
          displayData.list.userId === activeUser.data.user.id && (
            <div className="mb-6 flex gap-3">
              <Link
                to="/$username/collections/$slug/edit"
                params={{ username, slug }}
                className="transiton-colors ease rounded-md border border-white/5 bg-[#28292d] px-4 py-2 font-medium duration-150 hover:border-white/10 hover:bg-transparent"
              >
                Edit
              </Link>
              <Dialog>
                <Dialog.Trigger asChild>
                  <button className="ease cursor-pointer rounded-md border border-white/5 bg-[#28292d] px-4 py-2 font-medium transition-colors duration-150 hover:border-red-500 hover:bg-transparent">
                    Delete
                  </button>
                </Dialog.Trigger>
                <Dialog.Content
                  title="Delete this list?"
                  description="This action cannot be undone. This will permanently delete your
                      list and its content, including metadata such as likes, saves, and views."
                >
                  <Dialog.Footer>
                    <Dialog.Close asChild>
                      <button className="hover:text-foreground text-foreground border-background-light hover:bg-background-light inline-flex h-9 cursor-pointer items-center justify-center rounded-md border bg-transparent px-4 py-2 text-sm font-medium transition-colors">
                        Cancel
                      </button>
                    </Dialog.Close>
                    <Dialog.Close asChild>
                      <button
                        onClick={handleDelete}
                        className="text-foreground inline-flex h-9 cursor-pointer items-center justify-center rounded-md border-red-800 bg-red-700 px-4 py-2 text-sm font-medium transition-colors hover:bg-red-800"
                      >
                        Delete
                      </button>
                    </Dialog.Close>
                  </Dialog.Footer>
                </Dialog.Content>
              </Dialog>
            </div>
          )}

        <div className="flex w-full items-center justify-center gap-10 text-[#555] md:gap-6">
          <div className="flex items-center justify-center gap-2">
            <HeartIcon
              fill="#333"
              classes={`${isLiked && 'fill-[#FF153A]'} hover:fill-[#FF153A] cursor-pointer ease transition-all duration-150 active:scale-90 h-6`}
              onClick={() => updateLike()}
            />
            <p className="cursor-default">{formatter.format(likeCount)}</p>
          </div>

          <div className="flex items-center justify-center gap-2">
            <BookmarkIcon
              fill="#333"
              classes={`${isSaved && 'fill-[#32EC44]'} hover:fill-[#32EC44] cursor-pointer ease transition-all duration-150 active:scale-90 h-6`}
              onClick={() => updateSave()}
            />
            <p className="cursor-default">{formatter.format(saveCount)}</p>
          </div>
        </div>
      </aside>
    )
  );
}
