// src/components/navbar.tsx
import { useEffect, useRef, useState } from 'react';

import { Link, useLocation, useNavigate } from '@tanstack/react-router';
import {
  // Bolt,
  // CircleUserIcon,
  // Compass,
  Search,
  SquareLibrary,
} from 'lucide-react';
import { useHotkeys } from 'react-hotkeys-hook';

import CollectionsIcon from '@/components/icons/collections-icon';
import HomeIcon from '@/components/icons/home-icon';
import Tooltip from '@/components/tooltip';
import { TooltipProvider } from '@/components/ui/tooltip-ui';
import SearchBar from '@/features/search/components/search-bar';
import {
  SearchDialog,
  SearchDialogContent,
  SearchDialogDescription,
  SearchDialogHeader,
  SearchDialogTitle,
  SearchDialogTrigger,
} from '@/features/search/components/search-dialog';
import SearchResultList from '@/features/search/components/search-result-list';

export default function Navbar() {
  const [navbarEnabled, setNavbarEnabled] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  const searchBtn = useRef<HTMLButtonElement>(null);
  const lastKeyRef = useRef('');

  const navigate = useNavigate();
  const pathname = useLocation({
    select: (location) => location.pathname,
  });

  useHotkeys(
    'slash',
    (event) => {
      event.preventDefault();
      searchBtn.current?.click();
    },
    { enabled: navbarEnabled },
  );

  useHotkeys(
    'g',
    () => {
      lastKeyRef.current = 'g';
    },
    { enabled: navbarEnabled },
  );

  useHotkeys(
    'h, e, c, l, m, p',
    (event, _handler) => {
      if (lastKeyRef.current === 'g') {
        lastKeyRef.current = '';

        const pressedKey = event.key;

        switch (pressedKey) {
          case 'h':
            navigate({ to: '/home' });
            break;
          // case "e":
          //   navigate({ to: "/explore" });
          //   break;
          case 'c':
            navigate({ to: '/collections' });
            break;
          case 'l':
            navigate({ to: '/library', search: { filter: undefined } });
            break;
          case 'm':
            navigate({ to: '/profile' });
            break;
          case 'p':
            navigate({ to: '/preferences' });
            break;
        }
      }
    },
    {
      enabled: navbarEnabled,
    },
  );

  useEffect(() => {
    switch (pathname) {
      case '/':
      case '/login':
      case '/signup':
        setNavbarEnabled(false);
        break;
      default:
        setNavbarEnabled(true);
    }
  }, [pathname]);

  const tabs = [
    {
      id: 1,
      name: 'Home',
      href: '/home',
      key1: 'G',
      key2: 'H',
      icon: HomeIcon,
    },
    // {
    //   id: 2,
    //   name: "Explore",
    //   href: "/explore",
    //   key1: "G",
    //   key2: "E",
    //   icon: Compass,
    // },
    {
      id: 3,
      name: 'Collections',
      href: '/collections',
      key1: 'G',
      key2: 'C',
      icon: CollectionsIcon,
    },
    {
      id: 4,
      name: 'Library',
      href: '/library',
      key1: 'G',
      key2: 'L',
      icon: SquareLibrary,
    },
    // {
    //   id: 5,
    //   name: 'Profile',
    //   href: `/profile`,
    //   key1: 'G',
    //   key2: 'M',
    //   icon: CircleUserIcon,
    // },
    // {
    //   id: 6,
    //   name: 'Preferences',
    //   href: '/preferences',
    //   key1: 'G',
    //   key2: 'P',
    //   icon: Bolt,
    // },
  ];

  return (
    navbarEnabled && (
      <TooltipProvider>
        <div className="fixed right-0 bottom-2 left-0 z-50 mx-auto flex w-fit items-center justify-center gap-x-2">
          <div className="bg-background-dark/70 rounded-full border border-white/10 shadow-md backdrop-blur-sm">
            <nav className="relative flex gap-x-6 px-6 py-0">
              {tabs.map((tab) => {
                const Icon = tab.icon;
                return (
                  <Tooltip
                    key={tab.id}
                    side="top"
                    sideOffset={14}
                    content={tab.name}
                    key1={tab.key1}
                    key2={tab.key2}
                  >
                    <Link
                      to={tab.href}
                      activeProps={{
                        className: 'text-[#522aff]',
                      }}
                      activeOptions={{ exact: true }}
                      className="relative flex items-center justify-center bg-transparent text-neutral-200 transition-all duration-200 ease-in-out before:absolute before:top-0 before:bottom-0 before:my-auto before:size-8 before:rounded-full before:transition-all before:duration-200 before:ease-in-out hover:text-[#522aff] focus:outline-[#522aff]"
                    >
                      <Icon
                        width={24}
                        height={48}
                        strokeWidth={1.75}
                        className=""
                      />
                    </Link>
                  </Tooltip>
                );
              })}
            </nav>
          </div>

          <SearchDialog>
            <SearchDialogTrigger asChild>
              <button
                ref={searchBtn}
                className="relative text-neutral-200 outline-0 transition-colors duration-200 ease-in-out hover:text-[#522aff]"
              >
                <div className="bg-background-dark/70 flex size-12 items-center justify-center rounded-full border border-white/10 shadow-md backdrop-blur-sm">
                  <Tooltip side="top" sideOffset={14} content="Search" key1="/">
                    <Search
                      width={24}
                      height={48}
                      strokeWidth={1.75}
                      className="relative"
                    />
                  </Tooltip>
                </div>
              </button>
            </SearchDialogTrigger>

            <SearchDialogContent>
              <SearchDialogHeader className="sr-only">
                <SearchDialogTitle>Search</SearchDialogTitle>
                <SearchDialogDescription>
                  Search for a movie or tv series by name.
                </SearchDialogDescription>
              </SearchDialogHeader>

              <SearchBar
                searchQuery={searchQuery}
                setSearchQuery={setSearchQuery}
              />
              <SearchResultList searchQuery={searchQuery} />
            </SearchDialogContent>
          </SearchDialog>
        </div>
      </TooltipProvider>
    )
  );
}

// src/lib/components/shared/navbar.svelte
<script lang="ts">
	import Search from '@lucide/svelte/icons/search';

	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { page } from '$app/state';

	import CollectionsIcon from '$components/icons/collections-icon.svelte';
	import HomeIcon from '$components/icons/home-icon.svelte';
	import LibraryIcon from '$components/icons/library-icon.svelte';
	import SearchBar from '$components/search/search-bar.svelte';
	import SearchDialog from '$components/search/search-dialog.svelte';
	import SearchResultList from '$components/search/search-result-list.svelte';
	import { Dialog, DialogDescription, DialogTitle, DialogTrigger } from '$components/ui/dialog';
	import { TooltipProvider } from '$components/ui/tooltip';
	import { createGlobalShortcuts } from '$lib/utils/keyboard';

	import Tooltip from './tooltip.svelte';

	// Track which routes should show the navbar
	const pathname = $derived(page.url.pathname);
	const navbarEnabled = $derived.by(() => {
		switch (pathname) {
			case '/':
			case '/login':
			case '/signup':
				return false;
			default:
				return true;
		}
	});

	// False positive with reactivity. Ref does not need to be state.
	// svelte-ignore non_reactive_update
	let searchBtn: HTMLButtonElement | null = null;
	let searchQuery = $state('');

	// Set up keyboard shortcuts
	$effect(() => {
		if (!navbarEnabled) return;

		return createGlobalShortcuts([
			{ key: '/', callback: () => searchBtn?.click() },
			{ sequence: ['g', 'h'], callback: () => goto(resolve('/home')) },
			{ sequence: ['g', 'c'], callback: () => goto(resolve('/collections')) },
			{ sequence: ['g', 'l'], callback: () => goto(resolve('/library')) }
			// { sequence: ['g', 'm'], callback: () => goto(resolve('/profile')) },
			// { sequence: ['g', 'p'], callback: () => goto(resolve('/preferences')) }
		]);
	});

	// Define navigation tabs
	const tabs = [
		{
			id: 1,
			name: 'Home',
			href: '/home' as const,
			key1: 'G',
			key2: 'H',
			icon: HomeIcon
		},
		{
			id: 3,
			name: 'Collections',
			href: '/collections' as const,
			key1: 'G',
			key2: 'C',
			icon: CollectionsIcon
		},
		{
			id: 4,
			name: 'Library',
			href: '/library' as const,
			key1: 'G',
			key2: 'L',
			icon: LibraryIcon
		}
	];

	function isActive(href: string) {
		return pathname === href || (href !== '/home' && pathname.startsWith(href + '/'));
	}
</script>

{#if navbarEnabled}
	<TooltipProvider delayDuration={600}>
		<div
			class="fixed right-0 bottom-2 left-0 z-50 mx-auto flex w-fit items-center justify-center gap-x-2"
		>
			<div
				class="rounded-full border border-white/10 bg-background-dark/70 shadow-md backdrop-blur-sm"
			>
				<nav class="relative flex gap-x-5 px-5 py-0">
					{#each tabs as tab (tab.id)}
						{@const Component = tab.icon}
						<Tooltip side="top" sideOffset={14} content={tab.name} key1={tab.key1} key2={tab.key2}>
							<a
								href={resolve(tab.href)}
								class={[
									isActive(tab.href) ? 'text-[#522aff]' : 'text-neutral-200',
									'relative flex items-center justify-center bg-transparent transition-all duration-200 ease-in-out before:absolute before:top-0 before:bottom-0 before:my-auto before:size-8 before:rounded-full before:transition-all before:duration-200 before:ease-in-out hover:text-[#522aff] focus:outline-[#522aff]'
								]}
							>
								<Component />
							</a>
						</Tooltip>
					{/each}
				</nav>
			</div>

			<!-- Search dialog -->
			<Dialog>
				<Tooltip side="top" sideOffset={14} content="Search" key1="/">
					<DialogTrigger
						bind:ref={searchBtn}
						class="relative text-neutral-200 outline-0 transition-colors duration-200 ease-in-out hover:text-[#522aff]"
					>
						{#snippet child({ props })}
							<div
								{...props}
								class="flex size-11 items-center justify-center rounded-full border border-white/10 bg-background-dark/70 shadow-md backdrop-blur-sm"
							>
								<Search width={24} height={48} strokeWidth={1.5} class="relative" />
							</div>
						{/snippet}
					</DialogTrigger>
				</Tooltip>

				<SearchDialog>
					<DialogTitle class="sr-only">Search</DialogTitle>
					<DialogDescription class="sr-only">
						Search for a movie or tv series by name.
					</DialogDescription>

					<SearchBar bind:searchQuery />
					<SearchResultList query={searchQuery} />
				</SearchDialog>
			</Dialog>
		</div>
	</TooltipProvider>
{/if}
