// src/lib/components/shared/poster-grid.svelte
<script lang="ts">
	import type { ListItem } from '$types/lists';
	import type { Review } from '$types/ratings';

	import { resolve } from '$app/paths';

	import StarIcon from '$components/icons/star-icon.svelte';
	import Poster from '$components/shared/poster.svelte';
	import Tooltip from '$components/shared/tooltip.svelte';
	import { TooltipProvider } from '$components/ui/tooltip';
	import { slugify } from '$lib/utils/strings';

	type Props = {
		mediaArray: ListItem[] | Review<'movie' | 'tv'>[];
		isTooltipEnabled?: boolean;
		classes: string;
	};

	let { mediaArray, isTooltipEnabled: isEnabled, classes }: Props = $props();

	const filmRoute = '/films/[id]/[slug]';
	const seriesRoute = '/series/[id]/[slug]';
</script>

<div class={[classes, 'animate-fade-in-fast grid']}>
	{#if mediaArray.length > 0}
		{#each mediaArray as media, index (media.mediaId)}
			{@const route = media.mediaType === 'movie' ? filmRoute : seriesRoute}
			{@const titleSlug = slugify(media.title)}
			{@const rating = 'rating' in media && parseFloat(media.rating)}
			{@const loadStrategy = index < 18 ? 'eager' : 'lazy'}
			{@const fetchStrategy = index < 18 ? 'high' : 'low'}

			<!-- Tooltip Content -->
			{#snippet content()}
				<div class="max-w-48">
					<div class="w-full">
						<p class="font-semibold tracking-wide">{media.title}</p>
						<div class="my-1 flex justify-start">
							<StarIcon fill="#FFD43B" classes="h-4 w-4" />
							<span class="ml-1 font-semibold">{rating}</span>
						</div>
					</div>
				</div>
			{/snippet}

			<TooltipProvider>
				<Tooltip
					sideOffset={20}
					side="bottom"
					{content}
					{isEnabled}
					classes="bg-background-light border-white/10"
				>
					<a
						href={resolve(
							//@ts-expect-error Union type issue with resolve
							route,
							{ id: String(media.mediaId), slug: titleSlug }
						)}
						class="relative block rounded"
					>
						<Poster
							title={media.title}
							src={media.posterPath}
							fetchSize="w342"
							width={160}
							height={240}
							perspectiveEnabled={true}
							loading={loadStrategy}
							fetchPriority={fetchStrategy}
							classes="h-[165px] w-[110px] lg:w-[143px] lg:h-[213px] xl:h-[264px] xl:w-44"
						/>
					</a>
				</Tooltip>
			</TooltipProvider>
		{/each}
	{/if}
</div>

// src/components/poster-grid.tsx
import type { ListItem } from '@/types/lists';
import type { Review } from '@/types/ratings';

import { Link } from '@tanstack/react-router';

import { StarIcon } from '@/components/icons/star-icon';
import Poster from '@/components/poster';
import Tooltip from '@/components/tooltip';
import { TooltipProvider } from '@/components/ui/tooltip-ui';
import { slugify } from '@/lib/strings';
import { Route as filmRoute } from '@/routes/films/$id.$title';
import { Route as seriesRoute } from '@/routes/series/$id.$title';

type PosterGridProps = {
  media: ListItem[] | Review<'movie' | 'tv'>[];
  isTooltipEnabled?: boolean;
  classes: string;
};

export default function PosterGrid({
  media,
  isTooltipEnabled,
  classes,
}: PosterGridProps) {
  return (
    <div className={`${classes} animate-fade-in-fast grid`}>
      {media &&
        media.map((result, index) => {
          const mediaType = result.mediaType === 'movie' ? 'film' : 'series';
          const route =
            mediaType === 'film' ? filmRoute.fullPath : seriesRoute.fullPath;

          const titleSlug = slugify(result.title);
          const rating = 'rating' in result && parseFloat(result.rating);
          const loadingStrategy = index < 24 ? 'eager' : 'lazy';

          const tooltipContent = (
            <div className="max-w-48">
              <div className="w-full">
                <p className="font-semibold tracking-wide">{result.title}</p>
                <div className="my-1 flex justify-start">
                  <StarIcon fill="#FFD43B" classes="h-4 w-4" />
                  <span className="ml-1 font-semibold">{rating}</span>
                </div>
              </div>
            </div>
          );

          return (
            <TooltipProvider key={`${result.mediaId}-${index}`}>
              <Tooltip
                key={`${result.mediaId}-${index}`}
                sideOffset={25}
                side="bottom"
                content={tooltipContent}
                isEnabled={isTooltipEnabled}
                classes="bg-background-light border-white/10"
              >
                <Link
                  to={route}
                  params={{ id: result.mediaId.toString(), title: titleSlug }}
                  preload={false}
                  className="relative"
                >
                  <Poster
                    title={result.title}
                    src={result.posterPath}
                    fetchSize="w342"
                    width={160}
                    height={240}
                    perspectiveEnabled={true}
                    sizes="(min-width: 1280px) 176px, (min-width: 1024px) 160px, (min-width: 768px) 140px, 120px"
                    loading={loadingStrategy}
                    classes="xl:h-[264px] xl:w-44"
                  />
                </Link>
              </Tooltip>
            </TooltipProvider>
          );
        })}
    </div>
  );
}
