// src/lib/components/details/media-actions.svelte
<script lang="ts">
	import type { MediaDetails } from '$types/details';
	import type { SavedToList } from '$types/lists';

	import { createMutation, createQuery } from '@tanstack/svelte-query';
	import { updateReview } from '$services/actions';
	import { getListItem } from '$services/lists';
	import { getReview } from '$services/reviews';
	import { debounce } from '$utils/debounce';
	import { toast } from 'svelte-sonner';

	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';

	import MediaActionIcon from '$components/icons/media-actions-icons.svelte';
	import MediaActionsIcons from '$components/icons/media-actions-icons.svelte';
	import Tooltip from '$components/shared/tooltip.svelte';
	import * as Dialog from '$components/ui/dialog/index';
	import { TooltipProvider } from '$components/ui/tooltip';
	import { authClient } from '$lib/auth-client';

	import Lists from './lists.svelte';

	type Props = {
		media: MediaDetails;
	};

	let { media }: Props = $props();

	const authSession = authClient.useSession();
	const user = $derived($authSession.data?.user);
	const { id: mediaId, mediaType } = media;

	// Local state for optimistic updates
	let isLiked = $state(false);
	let isWatched = $state(false);
	let savedToLists: SavedToList[] = $state([]);

	const reviewQuery = createQuery(() => ({
		queryKey: ['review', mediaType, mediaId],
		queryFn: () => getReview(mediaType, mediaId),
		staleTime: 2 * 60 * 1000,
		gcTime: 5 * 60 * 1000,
		enabled: user !== undefined
	}));

	const listItemsQuery = createQuery(() => ({
		queryKey: ['listItems', mediaType, mediaId],
		queryFn: () => getListItem(mediaType, mediaId),
		staleTime: 3 * 60 * 1000,
		gcTime: 10 * 60 * 1000,
		enabled: user !== undefined
	}));

	const updateMutation = createMutation(() => ({
		mutationFn: async ({ field, value }: { field: 'liked' | 'watched'; value: boolean }) => {
			return await updateReview({ mediaType, mediaId, field, value });
		},
		onError: (error, variables) => {
			const { field, value } = variables;
			toast.error(`Failed to update ${field === 'liked' ? 'like' : 'watch'} status`);
			// Revert optimistic update on error
			if (field === 'liked') isLiked = !value;
			if (field === 'watched') isWatched = !value;
			console.error(error);
		}
	}));

	$effect(() => {
		if (reviewQuery.data) {
			isLiked = reviewQuery.data.liked;
			isWatched = reviewQuery.data.watched;
		}

		return () => {
			isLiked = false;
			isWatched = false;
		};
	});

	$effect(() => {
		if (listItemsQuery.data) {
			savedToLists = [listItemsQuery.data];
		}

		return () => (savedToLists = []);
	});

	// Debounced mutation functions
	const debouncedMutateLike = debounce(
		(value: boolean) => updateMutation.mutate({ field: 'liked', value }),
		1000
	);

	const debouncedMutateWatch = debounce(
		(value: boolean) => updateMutation.mutate({ field: 'watched', value }),
		1000
	);

	function handleClick(actionName: 'like' | 'watch') {
		if (!user) {
			toast.info('Please log in to continue');
			goto(resolve('/login'));
			return;
		}

		if (reviewQuery.data == null) {
			toast.info('Please submit a rating first');
			return;
		}

		if (actionName === 'like') {
			isLiked = !isLiked;
			debouncedMutateLike(isLiked);
		} else {
			isWatched = !isWatched;
			debouncedMutateWatch(isWatched);
		}
	}

	function handleListItemAdded(newListItem: SavedToList) {
		savedToLists = [...savedToLists, newListItem];
	}

	function handleListItemRemoved(listItemId: number) {
		savedToLists = savedToLists.filter((item) => item.listItemId !== listItemId);
	}

	const actions = [
		{
			id: 1,
			name: 'like' as const,
			content: 'Like',
			component: 'heart' as const,
			active: 'fill-[#FF153A]',
			hover: 'hover:fill-[#FF153A]'
		},
		{
			id: 2,
			name: 'watch' as const,
			content: 'Mark watched',
			component: 'eye' as const,
			active: 'fill-[#00e4f5]',
			hover: 'hover:fill-[#00e4f5]'
		}
	];
</script>

<div class="mt-3 flex w-full items-center justify-evenly gap-0 px-1.5">
	<TooltipProvider>
		{#each actions as action (action.id)}
			{@const isActive =
				(action.name === 'like' && isLiked) || (action.name === 'watch' && isWatched)}
			<Tooltip side="top" sideOffset={12} content={action.content}>
				<MediaActionIcon
					component={action.component}
					fill="#333"
					classes={[
						action.hover,
						isActive ? action.active : '',
						'cursor-pointer ease transition-all duration-150 active:scale-90 h-8'
					]}
					onclick={() => handleClick(action.name)}
				/>
			</Tooltip>
		{/each}

		<Dialog.Root>
			<Tooltip side="top" sideOffset={12} content="Save">
				<Dialog.Trigger>
					{#snippet child({ props })}
						<MediaActionsIcons
							{...props}
							component="bookmark"
							fill="#333"
							classes={[
								savedToLists.length > 0 ? 'fill-[#32EC44]' : '',
								'cursor-pointer hover:fill-[#32EC44] h-8'
							]}
						/>
					{/snippet}
				</Dialog.Trigger>
			</Tooltip>

			<Dialog.Content
				class="top-[30%] w-4/5 border border-white/5 bg-background p-6 caret-foreground outline-none md:top-[50%] md:w-1/2 md:max-w-lg"
			>
				<Dialog.Header class="mb-4">
					<Dialog.Title class="mb-0.5 tracking-wide">Update Collections</Dialog.Title>
					<Dialog.Description>Save or remove content from your collections</Dialog.Description>
				</Dialog.Header>

				<div class="h-[300px] animate-fade-in overflow-y-scroll">
					<!-- <CreateList /> -->
					<Lists
						{media}
						{savedToLists}
						onListItemAdded={handleListItemAdded}
						onListItemRemoved={handleListItemRemoved}
					/>
				</div>
			</Dialog.Content>
		</Dialog.Root>
	</TooltipProvider>
</div>

// src/features/details/components/media-actions.tsx
import type { MediaDetails } from '@/types/details';

import { useEffect, useState } from 'react';

import { useQuery } from '@tanstack/react-query';
import { toast } from 'sonner';

import {
  BookmarkIcon,
  EyeIcon,
  HeartIcon,
  // PenIcon,
} from '@/components/icons/media-actions-icons';
import Tooltip from '@/components/tooltip';
import { TooltipProvider } from '@/components/ui/tooltip-ui';
import CreateList from '@/features/details/components/create-list';
import Lists from '@/features/details/components/lists';
import ListsModal from '@/features/details/components/lists-modal';
import { useMediaActions } from '@/hooks/use-media-actions';
import { authClient } from '@/lib/auth-client';
import { getListItem } from '@/server/lists';
import { getReview } from '@/server/reviews';
import { useReviewStore } from '@/store/details/review-store';

type SavedToList = {
  listId: number;
  listItemId: number;
  mediaType: string;
  mediaId: number | null;
};

type ActionType = 'like' | 'watch' | 'review';

const actions = [
  {
    id: 1,
    name: 'like' as const,
    content: 'Like',
    icon: HeartIcon,
    active: 'fill-[#FF153A]',
    hover: 'hover:fill-[#FF153A]',
  },
  {
    id: 2,
    name: 'watch' as const,
    content: 'Mark watched',
    icon: EyeIcon,
    active: 'fill-[#00e4f5]',
    hover: 'hover:fill-[#00e4f5]',
  },
  // {
  //   id: 4,
  //   name: 'review' as const,
  //   content: 'Review',
  //   icon: PenIcon,
  //   active: 'fill-[#7468F3]',
  //   hover: 'hover:fill-[#7468F3]',
  // },
];

export default function MediaActions({ media }: Record<'media', MediaDetails>) {
  const [savedToLists, setSavedToLists] = useState<SavedToList[]>([]);

  const setIsLiked = useReviewStore.use.setIsLiked();
  const setIsWatched = useReviewStore.use.setIsWatched();

  const { data: authData } = authClient.useSession();

  const { id: mediaId, mediaType } = media;

  const { data: reviewData } = useQuery({
    queryKey: ['review', mediaType, mediaId],
    queryFn: async () => await getReview(mediaType, mediaId),
    staleTime: 2 * 60 * 1000,
    gcTime: 5 * 60 * 1000,
  });

  const { isLiked, isWatched, debouncedHandleClick } = useMediaActions(
    mediaType,
    mediaId,
    reviewData,
  );

  useEffect(() => {
    return () => {
      setIsLiked(false);
      setIsWatched(false);
    };
  }, [setIsLiked, setIsWatched]);

  useEffect(() => {
    async function fetchListItem() {
      try {
        const savedMedia = await getListItem(mediaType, mediaId);
        if (savedMedia) {
          setSavedToLists((prevState) => [...prevState, savedMedia]);
        }
      } catch (err) {
        toast.error('Failed to load saved list state');
      }
    }

    fetchListItem();

    return () => setSavedToLists([]);
  }, [mediaId, mediaType]);

  async function handleClick(actionName: ActionType) {
    if (actionName === 'review') {
      toast.error('Reviews are not supported yet!');
      return;
    }

    const user = authData?.user;

    if (!user || !user.id) {
      toast.info('Please log in to continue');
      return;
    }

    if (reviewData == null) {
      toast.info('Please submit a rating first');
      return;
    }

    if (actionName === 'like') {
      setIsLiked(!isLiked);
      return debouncedHandleClick(actionName, !isLiked);
    } else {
      setIsWatched(!isWatched);
      return debouncedHandleClick(actionName, !isWatched);
    }
  }

  return (
    <div className="mt-3 flex w-full items-center justify-evenly gap-0 px-1.5">
      <TooltipProvider>
        {actions.map((action) => {
          const Icon = action.icon;

          const isActive =
            (action.name === 'like' && isLiked) ||
            (action.name === 'watch' && isWatched);

          return (
            <Tooltip
              key={action.id}
              side="top"
              sideOffset={12}
              content={action.content}
            >
              {/* Div is necessary for tooltip to work */}
              <div>
                <Icon
                  fill="#333"
                  classes={`${action.hover} ${isActive && action.active} cursor-pointer ease transition-all duration-150 active:scale-90 h-8`}
                  onClick={() => handleClick(action.name)}
                />
              </div>
            </Tooltip>
          );
        })}

        <ListsModal>
          <Tooltip side="top" sideOffset={12} content={'Save'}>
            <ListsModal.Trigger asChild>
              {/* Div is necessary for tooltip to work */}
              <div>
                <BookmarkIcon
                  fill="#333"
                  classes={`${savedToLists.length > 0 && 'fill-[#32EC44]'} cursor-pointer hover:fill-[#32EC44] h-8`}
                />
              </div>
            </ListsModal.Trigger>
          </Tooltip>

          <ListsModal.Content
            title="Update Collections"
            description="Save or remove content from your collections"
          >
            <div className="animate-fade-in">
              <CreateList />
              <Lists
                media={media}
                savedToLists={savedToLists}
                setSavedToLists={setSavedToLists}
              />
            </div>
          </ListsModal.Content>
        </ListsModal>
      </TooltipProvider>
    </div>
  );
}
